title: Blast it, Create music with your sound card 
baseurl:  

markdown: redcarpet
redcarpet:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "strikethrough", "autolink"]

pygments: true

permalink: title.html
